export const CONFIG = {
    Z_INITIAL: 150,
    Z_STEP: 1,
    ROTATION_SPEED: 0.05,
    ANIMATION_SPEED: 1,
    CONTAINER_SIZE: { width: 400, height: 240 },
    SCALE_FACTOR: 4,
    MAX_PARTICLES: 6000,
    MAX_CONTAINERS: 4,
    FOG_FAR: 300,
    FOG_NEAR: 1,
    CAMERA_MOVE_STEP: 4,
    LOOK_MOVE_STEP: 2,
    CONTAINER_INTERVAL: 20,
    ID_THRESHOLD: 2000,
    COLOR_DELTA: 20,
    CAP_SEGMENTS: 2,
    RADIAL_SEGMENTS: 6
};